name: Deploy to Docker Hub and Remote Server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  DOCKER_IMAGE_NAME: mkh1n/tanderhack
  DOCKER_IMAGE_TAG: latest
  REMOTE_SERVER: tanderhack.ru
  REMOTE_USER: hacker
  REMOTE_PATH: /home/hacker/tanderhack
  CONTAINER_NAME: tanderhack
  CONTAINER_PORT: 8080

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          platforms: linux/amd64

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_LOGIN }}
          password: ${{ secrets.DOCKER_HUB_PWD }}

      - name: Build and push Docker image to Docker Hub
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ env.DOCKER_IMAGE_TAG }}
          file: ./app/Dockerfile